=== pieterh/energy-management-system/backend/EMS/Schemas/config.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "adapters": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "type": {
              "type": "string",
              "enum": [ "chargepoint", "smartmeter", "priceprovider" ]
            },
            "name": {
              "type": "string"
            },
            "driver": {
              "type": "object",
              "properties": {
                "assembly": {
                  "type": "string"
                },
                "type": {
                  "type": "string"
                }
              },
              "required": [
                "assembly",
                "type"
              ]
            }
          },
          "required": [
            "id",
            "type",
            "name",
            "driver"
          ]
        }
      ]
    },
    "instances": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "enabled": {
              "type": "boolean"
            },
            "adapterid": {
              "type": "string"
            },
            "config": {
              "type": "object"
            }
          },
          "required": [
            "id",
            "name",
            "enabled",
            "adapterid",
            "config"
          ]
        }
      ]
    },
    "web": {
      "type": "object",
      "properties": {
        "port": { "type": "number" },
        "host": { "type": "string" },
        "https": { "type": "boolean" },
        "jwt": {
          "type": "object",
          "properties": {
            "issuer": { "type": "string" },
            "audience": { "type": "string" },
            "expiration": { "type": "number" },
            "clockskew": { "type": "number" }
          },
          "required": [
            "issuer",
            "audience",
            "expiration",
            "clockskew"
          ]
        }
      },
      "required": [
        "port",
        "host"
      ]
    },
    "db": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [ "sqlite" ]
        },
        "name": { "type": "string" }
      },
      "required": [
        "type",
        "name"
      ]
    }
  },
  "required": [
    "adapters",
    "instances",
    "web"
  ]
}

=== pieterh/energy-management-system/docker/tests/config/config.json
{
  "adapters": [
    {
      "id": "f5069b64-628e-4cd9-bfad-e665be55c8b7",
      "type": "chargepoint",
      "name": "Alfen NG9xx",
      "driver": {
        "assembly": "AlfenNG9xx, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
        "type": "AlfenNG9xx.Alfen"
      }
    },
    {
      "id": "aab7376c-261a-4049-8c50-0e45e1d957c1",
      "type": "smartmeter",
      "name": "P1 Smartmeter",
      "driver": {
        "assembly": "P1SmartMeter, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
        "type": "P1SmartMeter.P1SmartMeter"
      }
    },
    {
      "id": "f5c39ed5-4fe7-4f81-b7bb-c477aac47fd4",
      "type": "priceprovider",
      "name": "EPEXSPOT Price Provider",
      "driver": {
        "assembly": "EPEXSPOT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
        "type": "EPEXSPOT.EPEXSPOT"
      }
    }
  ],
  "instances": [
    {
      "id": "36104380-b6a4-4dfe-821f-bb23005cd114",
      "name": "Alfen NG910",
      "adapterid": "f5069b64-628e-4cd9-bfad-e665be55c8b7",
      "config": {
        "host": "192.168.1.9",
        "port": 502
      }
    },
    {
      "id": "3af78bca-5a28-40ac-9c9a-d23ae2d3b700",
      "name": "SmartMeter - Iskra AM550",
      "adapterid": "aab7376c-261a-4049-8c50-0e45e1d957c1",
      "config": {
        "type": "LAN",
        "host": "192.168.1.7",
        "port": 3010
      }
    },
    {
      "id": "4c74eebb-3eb6-4168-945b-29cd6072d320",
      "name": "EPEXSPOT",
      "adapterid": "f5c39ed5-4fe7-4f81-b7bb-c477aac47fd4",
      "config": {
        "endpoint": "https://mijn.easyenergy.com"
      }
    }
  ],
  "web": {
    "port": 5000,
    "host": "localhost",
    "https": false,
    "jwt": {
      "issuer": "hems",
      "audience": "hems",
      "expiration": 60,
      "clockskew": 10
    }
  },
  "db": {
    "type": "sqlite",
    "name": "hems.db"
  }
}
